version: '3.8'

services:
  lamiautomation-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lamiautomation-app
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production