version: '3.8'

services:
  lamiautomation-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lamiautomation-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - lamiautomation-app